### ISSUE TITLE
tried to use on Observable

### ISSUE THREAD

**Issue by JustinGOSSES** [stac-utils/stac-layer#17]
I was interested in learning about stac and happened to try this repo as my entry point as I can often dabble more quickly in Observable with JavaScript than Python. 

Just wanted to flag that I couldn't get it to load such that I could call anything in an Observable notebook. Might not be anything wrong, but figured you might want to know how people are trying to use it as this repo is very new. 

https://observablehq.com/@justingosses/staclayer_test_1

Thanks for making it!

**Comment by m-mohr** [comment]
Thanks for reporting back. 

I'm a bit confused by the notebook though:
- Leaflet itself is looking weird (shuffled tiles)
- It seems data is not defined?
- Is this way of using import() something specific to Observable? I have only used the normal `import x from 'y'` from ES modules and `let x = require('y')` from Node.

Disclaimer: I've never used Observable before.

**Comment by DanielJDufour** [comment]
:wave: I love ObservableHQ! I'll try to take a look. The issue is probably that they expect AMD compliant bundles. I'll check our webpack config and see if we can fix this ASAP :-)

**Comment by m-mohr** [comment]
The debugger https://observablehq.com/@observablehq/module-require-debugger seems pretty interesting to test against :-)

**Comment by DanielJDufour** [comment]
Should we working now.  I published a new version of stac-layer that uses "@babel/polyfill".  Long story short, georaster expects this to be available.  I'll look at removing this weird requirement, but it will probably take a few months.  (Happy to go into the historical reasons).

The new version of stac-layer is a prerelease, so run `require("stac-layer@next")` or `npm install stac-layer@next`.  I figured we'd want to test it out before releasing a real new version of stac-layer.

You can see a fork of the  ObservableHQ notebook with the changes: https://observablehq.com/d/1c7799c13f11862a

@m-mohr , could you test out stac-browser with "stac-layer@next"?  If it works, I'll promote these changes to a real release.

**Comment by m-mohr** [comment]
Will do, thanks.

**Comment by JustinGOSSES** [comment]
Thank you for the help! 

Observable has a few early hurdles in terms of loading things then is pretty nice after that.

I've used the demo notebook provided and played around a bit more. https://observablehq.com/@justingosses/staclayer_test_1 

And thought I recognized your name @DanielJDufour , figured out it was from your code.gov work.

**Comment by m-mohr** [comment]
@DanielJDufour works like a charm!

**Comment by m-mohr** [comment]
@JustinGOSSES Your notebook clearly states the lack of documentation so I've created PR #19 - feel free to chime in and suggest improvements for what you think is still lacking. For your notebook, I think you could tweak the resolution as you mentioned the limited resolution and that was not documented yet.

**Comment by DanielJDufour** [comment]
@JustinGOSSES , awesome work.  I love the narrative form of the Notebook!  I just published a new version of stac-layer that includes the bundling fix.  You can now just `require("stac-layer")` and it should work.

**Comment by JustinGOSSES** [comment]
Importing stac-layer without the 'next' works fine now as said. 

Took a slightly different organization to this notebook exploring Microsoft's stac asset catalog https://observablehq.com/@justingosses/exploring-microsoft-planetary-computer-stac-catalog 

Will give the documentation needs a think and see if I can contribute anything
