### ISSUE TITLE
Enforce tile server

### ISSUE THREAD

**Issue by m-mohr** [stac-utils/stac-layer#24]
I can't figure out how I can enforce using the tile server instead of using client-side rendering. I think we had this in mind as a feature, but can't find out right now how to enforce it using config.

**Comment by DanielJDufour** [comment]
I think you just have to provide "tileUrlTemplate" string or "buildTileUrlTemplate" function.  And also, set useTileLayerAsFallback to false (or leave alone as undefined).

Do you want to completely disable client-side rendering or just use as a fallback?

If that doesn't fix it, could you provide a link to a page that it's not working on?

**Comment by m-mohr** [comment]
I want to disable it completely, will check your proposal. Thanks.

**Comment by DanielJDufour** [comment]
If you want to disable it completely even when tiler fails, I think we'll need to add an option for that.  Shouldn't take long though.  Will just add a few if statements in several section of the code.  What sort of option name would be best?
`disableClientSideRendering: true`, `clientSideRendering: false`, `enableClientSideRendering: true`, or something else? ...

**Comment by m-mohr** [comment]
To align with `useTileLayerAsFallback` maybe just `enforceTileLayer` so that it always uses the tileUrl.

**Comment by drwelby** [comment]
How big is the bill for the RDNT tiler? Are there cases where client-side rendering doesn't work, but the tiler will?

**Comment by m-mohr** [comment]
> How big is the bill for the RDNT tiler?

No clue, that's probably something that @HamedAlemo knows.

> Are there cases where client-side rendering doesn't work, but the tiler will?

I have not looked into what marbecutter can do, it hasn't been updated for quite a while, I think. I'd expect that larger GeoTiffs (i.e. not COGs) and more exotic settings (e.g. projections) work better with the tiler. But overall, we still need to investigate more. The client-side rendering in stac-browser is pretty new.

**Comment by drwelby** [comment]
>larger GeoTiffs (i.e. not COGs)

😨 yeah that could be bad

> more exotic settings (e.g. projections)

Our images are UTM and they work 🎉

**Comment by m-mohr** [comment]
I don't consider UTM exotic since S2 is using them. ;-)

**Comment by m-mohr** [comment]
I can confirm that giving a `tileUrlTemplate` and disabling `useTileLayerAsFallback` enforces the tile layer. So it's a matter of documentation. :-)
