### ISSUE TITLE
"Invalid byte order" on geotiffs

### ISSUE THREAD

**Issue by drwelby** [stac-utils/stac-layer#30]
See:

https://radiantearth.github.io/stac-browser/#/external/ard.maxar.com/samples/v4/sample-001/10/120020223032/2016-10-08/103001005D31F500.json

Loading any GeoTIFF layer throws:

```
stac-layer.min.js:2 caught error so checking geometry: TypeError: Invalid byte order value.
    at stac-layer.min.js:2:652030
    at u (stac-layer.min.js:2:452806)
    at Generator._invoke (stac-layer.min.js:2:452594)
    at Generator.next (stac-layer.min.js:2:453235)
    at h (stac-layer.min.js:2:488229)
    at a (stac-layer.min.js:2:488434)
```

**Comment by drwelby** [comment]
Geotiff.js throws the error on line 531 of https://geotiffjs.github.io/geotiff.js/geotiff.js.html

These images used to render so I don't think it's coming from the source image formatting

**Comment by DanielJDufour** [comment]
hey, just confirming that I saw this.  I'm beyond busy today and tomorrow, but will hopefully have some time this weekend to debug.  I'm very sorry about this!

**Comment by drwelby** [comment]
Found the source of the problem, our proxy is probably not passing through HEAD or OPTION requests to grab the first bytes of the file. If I connect to the S3 bucket URL instead then GeoTiff.JS can get the header information it needs.
