### ISSUE TITLE
buildTileUrlTemplate: href passed to function invalid

### ISSUE THREAD

**Issue by m-mohr** [stac-utils/stac-layer#31]
@drwelby reported in https://github.com/radiantearth/stac-browser/issues/126:

> https://radiantearth.github.io/stac-browser/#/external/ard.maxar.com/samples/v4/sample-001/10/120020223032/2016-10-08/103001005D31F500.json
> 
> On initial page load either `stac-browser` or `stac-layer` is trying to use the Radiant tiler but the URL isn't right:
> 
> `https://tiles.rdnt.io/tiles/10/163/395@2x?url=https%3A%2F%2Fard.maxar.com%2Fsamples%2Fv4%2Fsample-001%2F10%2F120020223032%2F2016-10-08%2F103001005D31F500.json%2F103001005D31F500-clouds.tif`
> 
> It's appending the asset name to the parent Item location.

**Comment by drwelby** [comment]
This also happens when not falling back to the tiler, see https://ard-cli-test.s3.amazonaws.com/sample-001/10/120020223032/2016-10-08/103001005D31F500.json

Same problem with the path: 

`https://ard.maxar.com/samples/v4/sample-001/10/120020223032/2016-10-08/103001005D31F500.json/103001005D31F500-visual.tif`

**Comment by drwelby** [comment]
I'm struggling getting a node dev environment working well enough to PR, but I think the link problems go away if you take advantage of `uri.js`

```javascript
var base = "https://ard.com/samples/103001005D31F500.json";

// URIs that are already absolute are passed through 
var asset_href = URI("https://stac.net/images/image.tif").absoluteTo(base); 
// >> "https://stac.net/images/image.tif"

// relative URIs are made absolute
var asset_href = URI("./image.tif").absoluteTo(base); 
// >> https://ard.com/samples/image.tif
```

**Comment by m-mohr** [comment]
Should be fixed.
