### ISSUE TITLE
Remove babel/polyfill ? 

### ISSUE THREAD

**Issue by rowanwins** [stac-utils/stac-layer#36]
The top line of `src/index.js` requires `@babel/polyfill`,  this probably isn't ideal size-wise (see this [from the babel docs](https://babel.dev/docs/en/babel-polyfill#size)). We should probably work out why it's here, is it for something specifically in this library or is it about trying to work around something upstream? And if babel is required we should probably move it to the build step in webpack or rollup etc.
Quickly scanning the code the optional chaining is the only thing that is new-ish, but even that has fairly wide support. So my gut feel is it can probably go.

**Comment by m-mohr** [comment]
I assume it is because of the optional chaining, which was (is?) not supported by the Vue v2 tooling (i.e. STAC Browser). But yeah, we should try to solve this.

**Comment by m-mohr** [comment]
Probably related to issues in STAC Browser in the beginning, see also #35 for some context. Let's remove it and then solve any upcoming issues downstream. @rowanwins This could probably be made part of #35?
