### ISSUE TITLE
Document release process

### ISSUE THREAD

**Issue by m-mohr** [stac-utils/stac-layer#47]
It would be nice to document the release process so that everyone could make it and we don't always need to bother @DanielJDufour :-)

**Comment by DanielJDufour** [comment]
agreed! I'll make a markdown file for that.

**Comment by DanielJDufour** [comment]
created it here. https://github.com/stac-utils/stac-layer/blob/main/RELEASE.md

definitely feel free to update or add more details.  just wanted to make sure that I got something documented for you asap
