### ISSUE TITLE
Pass or read min/max/nodata values

### ISSUE THREAD

**Issue by m-mohr** [stac-utils/stac-layer#5]
Right now it doesn't seem possible to either pass min/max and nodata values directly or read them via the raster extension. This should be made possible to give a more sensible default visualization.

**Comment by DanielJDufour** [comment]
@m-mohr . Definitely.  Do you happen to have an example of a STAC item with this information?

**Comment by m-mohr** [comment]
Yes, I've updated https://github.com/stac-utils/stac-layer/issues/7#issue-989213392 to have this metadata, but I'm not 100% sure it is actually correct, because it's generated externally. So take this just as a "how it could look like". But in addition to have it in a STAC item, it would be nice to also be able to override it via config.

And just to make sure: This is future work, which we might contract.

**Comment by m-mohr** [comment]
#54 will have functionality to easily get min/max values from a STAC so that we can use it here.

**Comment by m-mohr** [comment]
First attempt for no-data values: 9a1f8627
