### ISSUE TITLE
Migrate to stac-js?

### ISSUE THREAD

**Issue by m-mohr** [stac-utils/stac-layer#54]
I'm currently writing stac-js: https://github.com/m-mohr/stac-js

The aim is to consolidate code across projects (e.g. stac-layer, STAC Browser, STAC in OpenLayers etc). Whenever that's published we can probably refactor and simplify the code a lot...

**Comment by m-mohr** [comment]
Experimenting with this, which hopefully results in a PR soon.

**Comment by DanielJDufour** [comment]
awesome! 🚀
