### ISSUE TITLE
Default Import doesn't work with Vue

### ISSUE THREAD

**Issue by m-mohr** [stac-utils/stac-layer#6]
I'd expect that I can simply use stac-layer as such:

```js
import stacLayer from 'stac-layer';
let stacLayer = await stacLayer(data, options);
```

This gives me an error regarding e.g. optional chaining.

So, I have import and transpile it as follows:
```js
import stacLayer from 'stac-layer/src/index';
```

Also, I need to add `transpileDependencies: ['stac-layer'],` to vue.config.js.

This should be improved.

**Comment by DanielJDufour** [comment]
Good find!  I'll fix this.

**Comment by DanielJDufour** [comment]
@m-mohr , does this error happen appear when you run `npm run start` or does it appear in the browser?  If it happens in the browser, what browser are you using?

**Comment by m-mohr** [comment]
Sorry, I forgot to mention that I only get this during the build process (npm run build). num run start works fine.

**Comment by DanielJDufour** [comment]
@m-mohr , what version of node are you using?  When I run `node --version` I get `v15.13.0`.

**Comment by m-mohr** [comment]
v14.3.0

**Comment by m-mohr** [comment]
By the way, I'm also getting the following during build:

> [BABEL] Note: The code generator has deoptimised the styling of C:\Dev\stac-browser\node_modules\stac-layer\dist\stac-layer.min.js as it exceeds the max of 500KB.

Doesn't seem to be an issue though.

**Comment by m-mohr** [comment]
Just updated to v16.8.0. Testing it now gives me an endless error message (with all the stac-layer code!) for both npm run start and build.

**Comment by DanielJDufour** [comment]
This should work now.  Fixed with https://github.com/stac-utils/stac-layer/commit/e0dbc50bfd19cc62a186c5d74372a8d3b1b890eb and republished https://www.npmjs.com/package/stac-layer

**Comment by DanielJDufour** [comment]
@m-mohr , let me know if the new changes worked for you.

**Comment by m-mohr** [comment]
Thanks, I'll test this tomorrow!

**Comment by m-mohr** [comment]
This seems to work nicely now, thanks.
