### ISSUE TITLE
Incorrect placement of thumbnail image

### ISSUE THREAD

**Issue by james-hinton** [stac-utils/stac-layer#63]
The image below displays a leaflet app utilising the stac-layer to properly align the thumbnail with the map.
![1](https://github.com/stac-utils/stac-layer/assets/63542818/58311497-d086-485d-9a8e-8ab9ade96735)

Looking at the top left, we can see that there is good agreement between the placement of the thumbnail and the bounding box.
![2](https://github.com/stac-utils/stac-layer/assets/63542818/8c9303a0-65be-4afe-a518-a5a1f29f616d)

However, as we move towards the east and south, the image appears to be scaling incorrectly.
![3](https://github.com/stac-utils/stac-layer/assets/63542818/6b4e032e-8e32-46bd-b658-4a5a48057393)

This occurrence isn't isolated; it's noticeable across various items I've been looking at across other datasets in Planetary Computer.

STAC Item - https://planetarycomputer.microsoft.com/api/stac/v1/collections/esa-worldcover/items/ESA_WorldCover_10m_2021_v200_S57W069

STAC thumbnail - https://planetarycomputer.microsoft.com/api/data/v1/item/preview.png?collection=esa-worldcover&item=ESA_WorldCover_10m_2021_v200_S57W069&assets=map&colormap_name=esa-worldcover&format=png

I'm curious to know if this apparent scaling inconsistency is a known issue.

I have a theory that the root of this issue lies with irregularly shaped polygons. As the map extends downwards, the code seems to be struggling to scale the image accurately while maintaining spatial accuracy.

**Comment by james-hinton** [comment]
Just seen a candidate for the issue:
https://github.com/stac-utils/stac-layer/blob/main/src/index.js#L114

If the thumbnail scales to only 5 points in a BBOX rather than the polygon itself, it would scale incorrectly.

**Comment by DanielJDufour** [comment]
Hello.  Thanks for submitting this issue.  Happy to help get to the bottom of it.

Do you know what projection the thumbnail is in?  If the thumbnail is in a different projection than EPSG:3857 or EPSG:4326, that could potentially account for the issue.

**Comment by james-hinton** [comment]
Thanks for the quick response! 

The polygon and BBOX are both in 4326, but the PNG thumbnail doesn't have a coordinate system, it's just a regular PNG from the rendered_preview STAC asset.

**Comment by m-mohr** [comment]
For thumbnails without any metadata we can just make a guess anyway, right?
The other issue is that L.imageOverlay (that's what we use to render the image) only allows to provide bounds. I'm not sure whether it's really our aim with stac-layer to show previews pixel-perfect.

**Comment by james-hinton** [comment]
I agree with your points on the Leaflet limitations and the educated guess approach for thumbnails without metadata. Closing this issue makes sense at this stage. We'll keep track of any updates that could enable us to revisit this.
