### ISSUE TITLE
Conflict with react-leaflet-draw

### ISSUE THREAD

**Issue by james-hinton** [stac-utils/stac-layer#65]
Hi Matthias,

I know that you're still working on a v1 release of stac-layer, but just a quick heads up on a small issue I found with the code that's on the main branch right now. You may already know about this, but if not I thought best I let you know. 

When using react-leaflet-draw and stac-layer together, for some reason stac-layer stops the react-leaflet-draw from working. Perhaps it's just an issue with conflicting versions of leaflet, but I can't figure it out.

I made a small test repo to showcase this if you want to have a look : https://github.com/james-hinton/leaflet-draw-test/blob/master/src/App.js#L4 (if you want to try it out make sure to change the stac-layer in package.json to your local v1-beta directory)

So if that line of code is commented out, we have access to draw tools, but if its in, then we can't use any of the drawtool functionality. 

Any ideas on what could be going wrong as there's nothing coming up in the console? Also the stac-layer v1 code is looking really good thanks!

**Comment by james-hinton** [comment]
I can confirm that it also happens on non-React versions, I've proven that here: https://github.com/james-hinton/leaflet-draw-test/blob/master/further_tests/index.js#L4

So again, commenting out the import of stac-layer gets the draw-tools to work. 

To try and clarify a bit further. There are no errors in the logs, but I can see that leaflet-draw is successfully creating a HTML element `<div class="leaflet-draw leaflet-control"></div>` however, when stac-layer is imported, it's empty, but otherwise it is full of the normal draw tools.

**Comment by james-hinton** [comment]
master branch

**Comment by james-hinton** [comment]
I know that you're still working on it, thats why I was hesitant to say anything. But thought it'd be a good heads up just in case.

**Comment by m-mohr** [comment]
Thanks, I've cloned the repo and started a HTTP server in the further_tests folder, but the example doesn't run for me at all. How am I supposed to run this?

**Comment by m-mohr** [comment]
I just tried the react example, which gives me a map without stac-layer and edit functionality.
If I "uncomment" the stac-layer import, I'm not sure how to add stac-layer to the map in react?! Just the import doesn't change anything in the example, the edit still works.

**Comment by james-hinton** [comment]
You don't need to try and add a stacLayer. You should see that the draw tools on the top right are no longer visible. Does this not happen with you?

Also if you'd rather do the non-react version just use `npm install -g parcel-bundler ` and  `parcel index.html`

**Comment by james-hinton** [comment]
![Screenshot from 2023-07-31 16-50-27](https://github.com/stac-utils/stac-layer/assets/63542818/eb48bd29-55e6-4e69-a043-25465e505ab2)
![Screenshot from 2023-07-31 16-50-35](https://github.com/stac-utils/stac-layer/assets/63542818/b5dd973c-ed0f-4e0b-b588-b315f5bb18c0)

**Comment by m-mohr** [comment]
No, doesn't happen for me.

I changed the stac-layer import in the package.json: 
`    "stac-layer": "stac-utils/stac-layer#main",`

Removed the `#` in line 4 of the App.json.

`npm install` changed the package-lock.json changed heavily (and upgraded versions of the file itself), of course.
Maybe do the steps above, then delete node_module and package-lock.json and try again with fresh dependencies?

**Comment by james-hinton** [comment]
Ah. I cloned stac-layer and pointed it to it, but doing the ` "stac-layer": "stac-utils/stac-layer#main"` also fixed it for me.

Sorry for wasting your time, I really appreciate your help ! I'm not sure what I did wrong, but it works now.
